<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AspectoClaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AspectoClaveRepository extends EntityRepository
{
	public function findAllById($idCriterio,$isParent,$isArray){
		$em=$this->getEntityManager();
		if($isParent){
	        $dql   = "SELECT ac,c FROM AppWebBundle:AspectoClave ac
	        		JOIN ac.criterio c
	        		where c.idpadre=:id";
	    }else{
	    	$dql   = "SELECT ac,c FROM AppWebBundle:AspectoClave ac
	        		JOIN ac.criterio c
	        		where c.id=:id";
	    }
        $query = $em->createQuery($dql)->setParameter('id', $idCriterio);
        try {
                if($isArray)
                	return $query->getArrayResult();
                else
                	return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
	}
}
