<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConcursoCriterioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcursoCriterioRepository extends EntityRepository
{
	public function FindByConcurso($idConcurso){
        $em=$this->getEntityManager();
        $dql= "SELECT cp FROM AppWebBundle:ConcursoCriterio cp 
                JOIN cp.concurso c WHERE c.id=:id";
        $query=$em->createQuery($dql)->setParameter('id', $idConcurso);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
     public function FindByParentId($idConcurso,$idpadre){
        $em=$this->getEntityManager();
        $dql= "SELECT cp FROM AppWebBundle:ConcursoCriterio cp 
                JOIN cp.concurso c 
                WHERE c.id=:idconcurso
                AND cp.idpadre=:idpadre";
        $query=$em->createQuery($dql)
                ->setParameter('idconcurso', $idConcurso)
                ->setParameter('idpadre', $idpadre);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
}
