<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConflictoInteresEvaluadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConflictoInteresEvaluadorRepository extends EntityRepository
{
    public function FindByConflicto($idevaluador){
        $em=$this->getEntityManager();
        $dql= "SELECT ci FROM AppWebBundle:ConflictoInteresEvaluador ci 
                JOIN ci.evaluador ev WHERE ev.id=:id";
        $query=$em->createQuery($dql)->setParameter('id', $idevaluador);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
}
