<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConversacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversacionRepository extends EntityRepository
{

    public function findUserForChat(\App\WebBundle\Entity\Usuario $user){
		
       /* $grupos=$user->getGroups();
        foreach ($grupos as \App\WebBundle\Entity\GrupoEvakuacion $grupo) {
        	$evaluadores=$grupo->getEvaluadores();



        }*/
            
	}
}
