<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CriterioVisitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriterioVisitaRepository extends EntityRepository
{
	public function findByCriterio($id,$isArray=false){
		$em=$this->getEntityManager();
	        $dql   = "SELECT v FROM AppWebBundle:CriterioVisita v 
                        JOIN v.criterio c
                        where c.id=:id";
                $query = $em->createQuery($dql)->setParameter('id', $id);
                try {               	
                	return $query->getArrayResult();
                } catch (\Doctrine\ORM\NoResultException $e) {
                        return null;
                }
	}
        public function findArray($id){
                $em=$this->getEntityManager();
                $dql   = "SELECT v FROM AppWebBundle:CriterioVisita v WHERE v.id=:id";
                $query = $em->createQuery($dql)->setParameter('id', $id);
                try {                   
                        return $query->getArrayResult();
                } catch (\Doctrine\ORM\NoResultException $e) {
                        return null;
                }
        }
        public function findAllArray(){
                $em=$this->getEntityManager();
                $dql   = "SELECT v FROM AppWebBundle:CriterioVisita v";
                $query = $em->createQuery($dql);
                try {                   
                        return $query->getArrayResult();
                } catch (\Doctrine\ORM\NoResultException $e) {
                        return null;
                }
        }
}
