<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtapaConcursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapaConcursoRepository extends EntityRepository
{
    public function findAllEtapas($idConcurso){
        $em=$this->getEntityManager();
        $dql= "SELECT ec.id,e.id as etapaId,e.nombre,ec.fechaInicio,ec.fechaFin,ec.extendido,ec.fechaExtension 
            FROM AppWebBundle:Etapa e               
                LEFT JOIN e.etapasconcurso ec
                LEFT JOIN ec.concurso c
                WHERE c.id=:id or c.id is null
                ";
        $query=$em->createQuery($dql)->setParameter('id', $idConcurso);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
    
}
