<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtapaConcursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapaConcursoRepository extends EntityRepository
{
    public function findAllEtapas($idConcurso,$tipo){
        $em=$this->getEntityManager();
        $dql= "SELECT ec.id,e.id as etapaId,e.nombre,ec.fechaInicio,ec.fechaFin,ec.extendido,ec.fechaExtension 
            FROM AppWebBundle:Etapa e 
                JOIN e.tipoConcurso tc              
                LEFT JOIN e.etapasconcurso ec WITH ec.id IN (SELECT x.id FROM AppWebBundle:EtapaConcurso x JOIN x.concurso c WHERE c.id=:id)
                WHERE tc.id=$tipo
                ";
        $query=$em->createQuery($dql)->setParameter('id', $idConcurso);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
    
    public function findByEtapa($idconsurso,$idetapa){
        $em=$this->getEntityManager();
        $dql= "SELECT ec FROM AppWebBundle:EtapaConcurso ec 
                JOIN ec.concurso c
                JOIN ec.etapa e
                WHERE c.id=:idconcurso and e.id=:idetapa";
        $query=$em->createQuery($dql)
                ->setParameter('idconcurso', $idconsurso)
                ->setParameter('idetapa', $idetapa);
        try {
                return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }

    public function findByTipoEtapa($idconsurso,$idtipoetapa,$idtipoconcurso){
        $em=$this->getEntityManager();
        $dql= "SELECT ec FROM AppWebBundle:EtapaConcurso ec 
                JOIN ec.concurso c
                JOIN ec.etapa e
                JOIN e.tipoEtapa te
                JOIN e.tipoConcurso t
                WHERE c.id=:idconcurso 
                AND te.id=:idtipoetapa
                AND t.id=:idtipoconcurso";
        $query=$em->createQuery($dql)
                ->setParameter('idconcurso', $idconsurso)
                ->setParameter('idtipoetapa', $idtipoetapa)
                ->setParameter('idtipoconcurso', $idtipoconcurso);
        try {
                return $query->getArrayResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
    
}
