<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtapaConcursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapaConcursoRepository extends EntityRepository
{
    public function findAllEtapas($idConcurso,$tipo){
        $em=$this->getEntityManager();
        $dql= "SELECT ec.id,e.id as etapaId,e.nombre,ec.fechaInicio,ec.fechaFin,ec.extendido,ec.fechaExtension 
            FROM AppWebBundle:Etapa e 
                JOIN e.tipoConcurso tc              
                LEFT JOIN e.etapasconcurso ec
                LEFT JOIN ec.concurso c
                WHERE (c.id=:id or c.id is null)
                AND tc.id=$tipo
                ";
        $query=$em->createQuery($dql)->setParameter('id', $idConcurso);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
    
     public function findByEtapa($idconsurso,$idetapa){
        $em=$this->getEntityManager();
        $dql= "SELECT ec FROM AppWebBundle:EtapaConcurso ec 
                JOIN ec.concurso c
                JOIN ec.etapa e
                WHERE c.id=:idconcurso and e.id=:idetapa";
        $query=$em->createQuery($dql)
                ->setParameter('idconcurso', $idconsurso)
                ->setParameter('idetapa', $idetapa);
        try {
                return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
    
}
