<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionRepository extends EntityRepository
{
  public function FindEvaluacion($idevaluador,$idinscripcion,$idtipoetapa,$isArray=false){
        $em=$this->getEntityManager();
        $dql= "SELECT ev FROM AppWebBundle:Evaluacion ev
                JOIN ev.evaluador e
                JOIN ev.inscripcion i
                JOIN ev.tipoEtapa te
                WHERE e.id=:idevaluador 
                AND i.id=:idinscripcion
                AND te.id=:idtipoetapa";

        $query=$em->createQuery($dql)
            ->setParameter('idevaluador', $idevaluador)
            ->setParameter('idinscripcion', $idinscripcion)
             ->setParameter('idtipoetapa', $idtipoetapa);
        try {
                if($isArray)
                    return $query->getArrayResult();
                else
                    return $query->getOneOrNullResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }  
}
