<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluadorDisponibilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluadorDisponibilidadRepository extends EntityRepository
{
    public function FindByEvaluador($idusuario){
        $em=$this->getEntityManager();
        $dql= "SELECT ed FROM AppWebBundle:EvaluadorDisponibilidad ed 
                JOIN ed.evaluador e
                JOIN ed.dia d
                WHERE e.id=:id order by d.codigo asc";
        $query=$em->createQuery($dql)->setParameter('id', $idusuario);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
}
