<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoEvaluacionPostulanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoEvaluacionPostulanteRepository extends EntityRepository
{
    public function FindByGrupo($id,$isarray=false){
        $em=$this->getEntityManager();
        $dql= "SELECT gee,g,c,p FROM AppWebBundle:GrupoEvaluacionPostulante gee 
                JOIN gee.postulante p
                JOIN gee.grupo g
                JOIN g.concurso c
                WHERE g.id=:id or 0=:id ";
        $query=$em->createQuery($dql)->setParameter('id', $id);
        try {
                if($isarray)
                    return $query->getArrayResult();
                else
                    return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
    
    public function FindPostulantesDisponibles($id){       
        $conn = $this->getEntityManager()->getConnection('database_connection');//create a connection with your DB
        $sql="select p.* from postulante p inner JOIN inscripcion i on i.postulante_id=p.id
where i.concurso_id=$id and 
p.id not in(
select p.id from grupoevaluacionpostulante ge INNER JOIN postulante p on p.id=ge.postulante_id 
INNER JOIN grupoevaluacion g ON g.id=ge.grupoevaluacion_id where g.concurso_id=$id) ";                  
    
        $stmt = $conn->prepare($sql);  
        $stmt->execute(); 
        
        return $result=$stmt->fetchAll(); 
    }
    
}
