<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoEvaluacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoEvaluacionRepository extends EntityRepository
{
	 public function FindAllPaginator($paginator,$page,$limit){
        $em=$this->getEntityManager();
        $dql   = "SELECT p FROM AppWebBundle:GrupoEvaluacion p order by p.nombre";
        $query = $em->createQuery($dql);
        $pagination = $paginator->paginate($query,$page,$limit);
        return $pagination;
    }
}
