<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoEvaluacionPostulanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoEvaluacionPostulanteRepository extends EntityRepository
{
    public function FindByGrupo($id){
        $em=$this->getEntityManager();
        $dql= "SELECT gee FROM AppWebBundle:GrupoEvaluacionPostulante gee 
                JOIN gee.grupo g
                WHERE g.id=:id ";
        $query=$em->createQuery($dql)->setParameter('id', $id);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
}
