<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscripcionEvaluadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscripcionEvaluadorRepository extends EntityRepository
{
    public function IsRegister($idEvaluador,$idConcurso){
        $em=$this->getEntityManager();
        $dql= "
        SELECT count(i.id) FROM AppWebBundle:InscripcionEvaluador i
        JOIN i.concurso c 
        JOIN i.evaluador p
        WHERE c.id=:codConcurso and p.id=:codEvaluador";
        $query=$em->createQuery($dql)
                ->setParameter('codConcurso', $idConcurso)
                ->setParameter('codEvaluador', $idEvaluador);
        try {
                return ($query->getSingleResult()==0)?false:true;
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
    public function GetConcursos($idEvaluador){
        $em=$this->getEntityManager();
        $dql= "
        SELECT i FROM AppWebBundle:InscripcionEvaluador i
        JOIN i.concurso c 
        JOIN i.evaluador p
        WHERE p.id=:codEvaluador";
        $query=$em->createQuery($dql)
                  ->setParameter('codEvaluador', $idEvaluador);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
}
