<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
     public function FindByParent($idperfil, $idpadre){
        $em=$this->getEntityManager();
        $dql= "SELECT m FROM AppWebBundle:Menu m 
                JOIN m.perfiles acc
                WHERE m.idpadre=:idpadre 
                AND acc.id=:idperfil";
        $query=$em->createQuery($dql)
                ->setParameter('idpadre', $idpadre)
                ->setParameter('idperfil', $idperfil);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
     public function FindByParentId($idpadre){
        $em=$this->getEntityManager();
        $dql= "SELECT m FROM AppWebBundle:Menu m 
                
                WHERE m.idpadre=:idpadre 
                ";
        $query=$em->createQuery($dql)
                ->setParameter('idpadre', $idpadre);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
   
}
