<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaRepository extends EntityRepository
{
	public function FindByUsuario($idusuario){
        $em=$this->getEntityManager();
        $dql= "SELECT n FROM AppWebBundle:Nota n JOIN n.usuario u WHERE u.id=:id";
        $query=$em->createQuery($dql)->setParameter('id', $idusuario);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
}
