<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilRepository extends EntityRepository
{
    public function FindAllPaginator($paginator,$page,$limit){
        $em=$this->getEntityManager();
        $dql   = "SELECT p FROM AppWebBundle:Perfil p";
        $query = $em->createQuery($dql);
        $pagination = $paginator->paginate($query,$page,$limit);
        return $pagination;
    }
    public function GetAccesos($id){
        $conn = $this->getEntityManager()->getConnection('database_connection');//create a connection with your DB
		$sql="select GROUP_CONCAT(menu_id) as ids from acceso where perfil_id=$id";   //Your sql 
    	$stmt = $conn->prepare($sql);  
    	$stmt->execute(); 
    	$result=$stmt->fetch(); 
    	return  $result['ids'];  
    }
    public function RemoveAllAccesos($idperfil){
        $conn = $this->getEntityManager()->getConnection('database_connection');//create a connection with your DB

        $sql="delete from  acceso where perfil_id=$idperfil";                   
        $stmt = $conn->prepare($sql);  
        $stmt->execute(); 
         
    }

}
