<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostulanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulanteRepository extends EntityRepository
{
    public function getPostulantes($id){
        $em=$this->getEntityManager();
        $dql= "SELECT p FROM AppWebBundle:Postulante p 
                JOIN p.grupos g
                WHERE g.id=:id ";
        $query=$em->createQuery($dql)
                ->setParameter('id', $id);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
    public function FindByUser($idusuario){
        $em=$this->getEntityManager();
        $dql= "SELECT p FROM AppWebBundle:Postulante p 
                JOIN p.usuario u
                WHERE u.id=:id";
        $query=$em->createQuery($dql)
        ->setParameter('id', $idusuario);
        try {
                return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
               return null;
        }
    }
   
}
