<?php

namespace App\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostulanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulanteRepository extends EntityRepository
{
    public function getPostulantes($id){
        $em=$this->getEntityManager();
        $dql= "SELECT p FROM AppWebBundle:Postulante p 
                JOIN p.grupos g
                WHERE g.id=:id ";
        $query=$em->createQuery($dql)
                ->setParameter('id', $id);
        try {
                return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
                return null;
        }
    }
    public function FindByUser($idusuario){
        $em=$this->getEntityManager();
        $dql= "SELECT p FROM AppWebBundle:Postulante p 
                JOIN p.usuario u
                WHERE u.id=:id";
        $query=$em->createQuery($dql)
        ->setParameter('id', $idusuario);
        try {
                return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
               return null;
        }
    }
    public function FindAllPaginator($paginator,$page,$limit){
        $em=$this->getEntityManager();
        $dql   = "SELECT p FROM AppWebBundle:Postulante p";
        $query = $em->createQuery($dql);
        $pagination = $paginator->paginate($query,$page,$limit);
        return $pagination;
    }
     public function getEvaluadoresConflictosInteres($idgrupo,$ruc){
        $conn = $this->getEntityManager()->getConnection('database_connection');//create a connection with your DB
        $sql="select e.* from grupoevaluacionevaluador  ge 
join evaluador e on e.id=ge.evaluador_id 
JOIN conflictointeresevaluador ci ON ci.evaluador_id=e.id
where ge.grupoevaluacion_id=$idgrupo
AND ci.ruc='$ruc'";                  
    
        $stmt = $conn->prepare($sql);  
        $stmt->execute(); 
        return $result=$stmt->fetchAll(); 
        
    }
   
}
